"use client";
import { useState } from 'react';
import { Button, PageHeader, SectionCard } from '@/components/ui';
import { useApp } from '@/components/app-shell';
import { stages } from '@/lib/mock-data';
import { ProfileSettings } from '@/components/profile-settings';
export default function SettingsPage() {
 const { settings, saveSettings, language, setLanguage } = useApp(); const [name, setName] = useState(settings.name); const [currency, setCurrency] = useState(settings.currency); const [notifications, setNotifications] = useState(settings.notifications); const [saved, setSaved] = useState(false);
 return <div><PageHeader eyebrow="Workspace controls" title="Settings" description="Preferences for your Supabase workspace." /><form onChange={() => setSaved(false)} onSubmit={e => { e.preventDefault(); if (!name.trim()) return; saveSettings({ name: name.trim(), currency, notifications }); setSaved(true); }} className="max-w-3xl space-y-5"><SectionCard title="Workspace"><div className="grid gap-4 p-5 sm:grid-cols-2"><label>Workspace name<input required maxLength={100} value={name} onChange={e => setName(e.target.value)} className="form-input" /></label><label>Default currency<select value={currency} onChange={e => setCurrency(e.target.value as 'KGS' | 'USD')} className="form-input"><option>KGS</option><option>USD</option></select></label><label>Navigation language<select value={language} onChange={e => setLanguage(e.target.value as 'en' | 'ru')} className="form-input"><option value="en">English</option><option value="ru">Русский</option></select></label><label className="flex items-center gap-2"><input type="checkbox" checked={notifications} onChange={e => setNotifications(e.target.checked)} />Show task notifications</label><p className="text-xs text-slate-500 sm:col-span-2">Language applies to navigation and catalogue labels. Currency is used for new deals; existing amounts are not converted.</p></div></SectionCard><Button type="submit" variant="primary" disabled={!name.trim()}>Save changes</Button>{saved && <p role="status" className="text-emerald-700">Preferences updated. Wait for “Saved to Supabase” above before leaving.</p>}<SectionCard title="Pipeline stages"><div className="p-5"><p className="mb-3 text-sm text-slate-500">These stages are fixed for now.</p><div className="flex flex-wrap gap-2">{stages.map(stage => <span key={stage} className="rounded-lg bg-slate-100 px-3 py-2">{stage}</span>)}</div></div></SectionCard><SectionCard title="Connections and accounts"><div className="space-y-3 p-5 text-sm text-slate-600"><p>Accounts and workspace data are handled by Supabase Auth and Row Level Security.</p><p>2GIS map tiles require a MapGL key. Business search requires a separate Places API subscription and server key.</p></div></SectionCard></form><div className="mt-5 max-w-3xl"><ProfileSettings /></div></div>;
}
